site: Duenam

collections:
  pages:
    output: true
    permalink: {{site.baseurl}}/:name
  posts:
    output: true
    permalink: {{site.baseurl}}/blog/:slug
  projects:
    output: true
    permalink: {{site.baseurl}}/project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

gallery_types:
  carousel: Carousel
  grid: Grid
grid_columns:
  two: Two
  three: Three
  four: Four


# URL
url:                "https://duenam.com" # the base hostname & protocol for your site
# url:                "https://duenam.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "/Duet_due" # the subpath of your site, e.g. /blog
